"""Initial schema with case system

Revision ID: 9cf7b38a44b0
Revises: 
Create Date: 2026-01-30 17:10:06.388730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf7b38a44b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammatical_cases',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('name_basque', sa.String(length=50), nullable=False),
    sa.Column('suffix', sa.String(length=30), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('example_singular', sa.String(length=100), nullable=False),
    sa.Column('example_plural', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('grammatical_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grammatical_cases_level'), ['level'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('words',
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('french_word', sa.String(length=255), nullable=True),
    sa.Column('basque_lemma', sa.String(length=255), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('part_of_speech_fr', sa.String(length=100), nullable=True),
    sa.Column('lemma', sa.String(length=255), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('frequency_count', sa.Integer(), nullable=True),
    sa.Column('anki_note_id', sa.BigInteger(), nullable=True),
    sa.Column('anki_interval', sa.Integer(), nullable=False),
    sa.Column('anki_ease', sa.Float(), nullable=False),
    sa.Column('anki_last_review', sa.DateTime(), nullable=True),
    sa.Column('is_known', sa.Boolean(), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_anki_note_id'), ['anki_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_basque_lemma'), ['basque_lemma'], unique=False)
        batch_op.create_index('ix_words_french_basque', ['french_word', 'basque_lemma'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_french_word'), ['french_word'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_frequency_rank'), ['frequency_rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_is_known'), ['is_known'], unique=False)
        batch_op.create_index('ix_words_language_frequency', ['language', 'frequency_rank'], unique=False)
        batch_op.create_index('ix_words_language_word', ['language', 'word'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_word'), ['word'], unique=False)

    op.create_table('sentences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_word_id', sa.Integer(), nullable=False),
    sa.Column('target_case_id', sa.Integer(), nullable=True),
    sa.Column('sentence_text', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('french_text', sa.Text(), nullable=True),
    sa.Column('target_number', sa.String(length=20), nullable=False),
    sa.Column('target_form', sa.String(length=255), nullable=True),
    sa.Column('context_word_ids_json', sa.Text(), nullable=True),
    sa.Column('audio_basque_path', sa.String(length=500), nullable=True),
    sa.Column('audio_french_path', sa.String(length=500), nullable=True),
    sa.Column('anki_note_id', sa.BigInteger(), nullable=True),
    sa.Column('anki_interval', sa.Integer(), nullable=False),
    sa.Column('anki_last_review', sa.DateTime(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('times_shown', sa.Integer(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_case_id'], ['grammatical_cases.id'], ),
    sa.ForeignKeyConstraint(['target_word_id'], ['words.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_index('ix_sentences_anki_note', ['anki_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentences_anki_note_id'), ['anki_note_id'], unique=False)
        batch_op.create_index('ix_sentences_target_case', ['target_case_id'], unique=False)
        batch_op.create_index('ix_sentences_user_language', ['user_id', 'language'], unique=False)
        batch_op.create_index('ix_sentences_user_target', ['user_id', 'target_word_id'], unique=False)

    op.create_table('user_case_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('sentences_generated', sa.Integer(), nullable=False),
    sa.Column('sentences_reviewed', sa.Integer(), nullable=False),
    sa.Column('avg_interval', sa.Float(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('successful_reviews', sa.Integer(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['grammatical_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'case_id', name='uq_user_case')
    )
    with op.batch_alter_table('user_case_progress', schema=None) as batch_op:
        batch_op.create_index('ix_user_case_progress_user', ['user_id'], unique=False)
        batch_op.create_index('ix_user_case_progress_user_unlocked', ['user_id', 'unlocked'], unique=False)

    op.create_table('user_word_states',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('next_review', sa.Date(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('successful_reviews', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_word_states', schema=None) as batch_op:
        batch_op.create_index('ix_user_word_states_user_mastery', ['user_id', 'mastery_level'], unique=False)
        batch_op.create_index('ix_user_word_states_user_next_review', ['user_id', 'next_review'], unique=False)
        batch_op.create_index('ix_user_word_states_user_word', ['user_id', 'word_id'], unique=True)

    op.create_table('reviews',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('ease_factor_before', sa.Float(), nullable=True),
    sa.Column('interval_before', sa.Integer(), nullable=True),
    sa.Column('ease_factor_after', sa.Float(), nullable=True),
    sa.Column('interval_after', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('ix_reviews_user_reviewed_at', ['user_id', 'reviewed_at'], unique=False)
        batch_op.create_index('ix_reviews_user_word', ['user_id', 'word_id'], unique=False)

    op.create_table('sentence_words',
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('case_used', sa.String(length=50), nullable=True),
    sa.Column('form_used', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('is_target', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentence_words', schema=None) as batch_op:
        batch_op.create_index('ix_sentence_word_is_target', ['is_target'], unique=False)
        batch_op.create_index('ix_sentence_word_sentence', ['sentence_id'], unique=False)
        batch_op.create_index('ix_sentence_word_unique', ['sentence_id', 'word_id', 'position'], unique=True)
        batch_op.create_index('ix_sentence_word_word', ['word_id'], unique=False)
        batch_op.create_index('ix_sentence_word_word_case', ['word_id', 'case_used'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentence_words', schema=None) as batch_op:
        batch_op.drop_index('ix_sentence_word_word_case')
        batch_op.drop_index('ix_sentence_word_word')
        batch_op.drop_index('ix_sentence_word_unique')
        batch_op.drop_index('ix_sentence_word_sentence')
        batch_op.drop_index('ix_sentence_word_is_target')

    op.drop_table('sentence_words')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_reviews_user_word')
        batch_op.drop_index('ix_reviews_user_reviewed_at')

    op.drop_table('reviews')
    with op.batch_alter_table('user_word_states', schema=None) as batch_op:
        batch_op.drop_index('ix_user_word_states_user_word')
        batch_op.drop_index('ix_user_word_states_user_next_review')
        batch_op.drop_index('ix_user_word_states_user_mastery')

    op.drop_table('user_word_states')
    with op.batch_alter_table('user_case_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_user_case_progress_user_unlocked')
        batch_op.drop_index('ix_user_case_progress_user')

    op.drop_table('user_case_progress')
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index('ix_sentences_user_target')
        batch_op.drop_index('ix_sentences_user_language')
        batch_op.drop_index('ix_sentences_target_case')
        batch_op.drop_index(batch_op.f('ix_sentences_anki_note_id'))
        batch_op.drop_index('ix_sentences_anki_note')

    op.drop_table('sentences')
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_word'))
        batch_op.drop_index('ix_words_language_word')
        batch_op.drop_index('ix_words_language_frequency')
        batch_op.drop_index(batch_op.f('ix_words_is_known'))
        batch_op.drop_index(batch_op.f('ix_words_frequency_rank'))
        batch_op.drop_index(batch_op.f('ix_words_french_word'))
        batch_op.drop_index('ix_words_french_basque')
        batch_op.drop_index(batch_op.f('ix_words_basque_lemma'))
        batch_op.drop_index(batch_op.f('ix_words_anki_note_id'))

    op.drop_table('words')
    op.drop_table('users')
    with op.batch_alter_table('grammatical_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grammatical_cases_level'))

    op.drop_table('grammatical_cases')
    # ### end Alembic commands ###
